-- Monitor size: 8 × 6 characters
local monitor = peripheral.find('monitor')
term.redirect(monitor)
monitor.clear()
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(1,1)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(2,1)
monitor.write(' ')
monitor.setBackgroundColor(colors.green)
monitor.setCursorPos(3,1)
monitor.write(' ')
monitor.setBackgroundColor(colors.brown)
monitor.setCursorPos(4,1)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(5,1)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(6,1)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(7,1)
monitor.write(' ')
monitor.setBackgroundColor(colors.green)
monitor.setCursorPos(8,1)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(1,2)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(2,2)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(3,2)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(4,2)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(5,2)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(6,2)
monitor.write(' ')
monitor.setBackgroundColor(colors.green)
monitor.setCursorPos(7,2)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(8,2)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(1,3)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(2,3)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(3,3)
monitor.write(' ')
monitor.setBackgroundColor(colors.brown)
monitor.setCursorPos(4,3)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(5,3)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(6,3)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(7,3)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(8,3)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(1,4)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(2,4)
monitor.write(' ')
monitor.setBackgroundColor(colors.brown)
monitor.setCursorPos(3,4)
monitor.write(' ')
monitor.setBackgroundColor(colors.brown)
monitor.setCursorPos(4,4)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(5,4)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(6,4)
monitor.write(' ')
monitor.setBackgroundColor(colors.green)
monitor.setCursorPos(7,4)
monitor.write(' ')
monitor.setBackgroundColor(colors.green)
monitor.setCursorPos(8,4)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(1,5)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(2,5)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(3,5)
monitor.write(' ')
monitor.setBackgroundColor(colors.brown)
monitor.setCursorPos(4,5)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(5,5)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(6,5)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(7,5)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(8,5)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(1,6)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(2,6)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(3,6)
monitor.write(' ')
monitor.setBackgroundColor(colors.gray)
monitor.setCursorPos(4,6)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(5,6)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(6,6)
monitor.write(' ')
monitor.setBackgroundColor(colors.black)
monitor.setCursorPos(7,6)
monitor.write(' ')
monitor.setBackgroundColor(colors.lightGray)
monitor.setCursorPos(8,6)
monitor.write(' ')
